-- migrate:up
insert into comment (user_id, posting_id, comment) values (2, 47, 'Account Coordinator');
insert into comment (user_id, posting_id, comment) values (9, 10, 'Structural Analysis Engineer');
insert into comment (user_id, posting_id, comment) values (10, 10, 'Administrative Assistant I');
insert into comment (user_id, posting_id, comment) values (8, 43, 'Senior Cost Accountant');
insert into comment (user_id, posting_id, comment) values (9, 40, 'Compensation Analyst');
insert into comment (user_id, posting_id, comment) values (2, 17, 'Office Assistant III');
insert into comment (user_id, posting_id, comment) values (6, 9, 'Quality Control Specialist');
insert into comment (user_id, posting_id, comment) values (8, 5, 'Social Worker');
insert into comment (user_id, posting_id, comment) values (11, 22, 'Computer Systems Analyst II');
insert into comment (user_id, posting_id, comment) values (11, 49, 'Junior Executive');
insert into comment (user_id, posting_id, comment) values (2, 40, 'Desktop Support Technician');
insert into comment (user_id, posting_id, comment) values (8, 35, 'Marketing Manager');
insert into comment (user_id, posting_id, comment) values (1, 32, 'Senior Sales Associate');
insert into comment (user_id, posting_id, comment) values (10, 48, 'Recruiter');
insert into comment (user_id, posting_id, comment) values (1, 1, 'Data Coordiator');
insert into comment (user_id, posting_id, comment) values (7, 36, 'Computer Systems Analyst III');
insert into comment (user_id, posting_id, comment) values (6, 27, 'Executive Secretary');
insert into comment (user_id, posting_id, comment) values (2, 42, 'Technical Writer');
insert into comment (user_id, posting_id, comment) values (6, 28, 'GIS Technical Architect');
insert into comment (user_id, posting_id, comment) values (9, 39, 'Speech Pathologist');
insert into comment (user_id, posting_id, comment) values (1, 10, 'Desktop Support Technician');
insert into comment (user_id, posting_id, comment) values (1, 10, 'Accountant IV');
insert into comment (user_id, posting_id, comment) values (8, 48, 'Help Desk Technician');
insert into comment (user_id, posting_id, comment) values (5, 36, 'Software Engineer II');
insert into comment (user_id, posting_id, comment) values (11, 44, 'Database Administrator IV');
insert into comment (user_id, posting_id, comment) values (7, 29, 'Sales Representative');
insert into comment (user_id, posting_id, comment) values (4, 11, 'Software Consultant');
insert into comment (user_id, posting_id, comment) values (1, 3, 'Web Designer I');
insert into comment (user_id, posting_id, comment) values (11, 18, 'Legal Assistant');
insert into comment (user_id, posting_id, comment) values (9, 41, 'Office Assistant IV');
insert into comment (user_id, posting_id, comment) values (1, 2, 'Senior Cost Accountant');
insert into comment (user_id, posting_id, comment) values (11, 20, 'VP Product Management');
insert into comment (user_id, posting_id, comment) values (7, 9, 'Editor');
insert into comment (user_id, posting_id, comment) values (7, 19, 'Marketing Assistant');
insert into comment (user_id, posting_id, comment) values (7, 38, 'Engineer II');
insert into comment (user_id, posting_id, comment) values (8, 30, 'Help Desk Operator');
insert into comment (user_id, posting_id, comment) values (1, 10, 'VP Quality Control');
insert into comment (user_id, posting_id, comment) values (11, 33, 'Assistant Manager');
insert into comment (user_id, posting_id, comment) values (11, 17, 'Financial Advisor');
insert into comment (user_id, posting_id, comment) values (5, 3, 'VP Marketing');
insert into comment (user_id, posting_id, comment) values (9, 35, 'Staff Scientist');
insert into comment (user_id, posting_id, comment) values (6, 5, 'Graphic Designer');
insert into comment (user_id, posting_id, comment) values (11, 24, 'Occupational Therapist');
insert into comment (user_id, posting_id, comment) values (7, 9, 'Graphic Designer');
insert into comment (user_id, posting_id, comment) values (6, 5, 'Actuary');
insert into comment (user_id, posting_id, comment) values (3, 44, 'Electrical Engineer');
insert into comment (user_id, posting_id, comment) values (7, 35, 'Research Associate');
insert into comment (user_id, posting_id, comment) values (10, 23, 'Account Coordinator');
insert into comment (user_id, posting_id, comment) values (4, 2, 'Community Outreach Specialist');
insert into comment (user_id, posting_id, comment) values (6, 44, 'Technical Writer');
insert into comment (user_id, posting_id, comment) values (4, 29, 'Compensation Analyst');
insert into comment (user_id, posting_id, comment) values (3, 37, 'Software Consultant');
insert into comment (user_id, posting_id, comment) values (4, 26, 'Account Representative IV');
insert into comment (user_id, posting_id, comment) values (10, 9, 'Electrical Engineer');
insert into comment (user_id, posting_id, comment) values (4, 15, 'Nurse Practicioner');
insert into comment (user_id, posting_id, comment) values (9, 13, 'Marketing Manager');
insert into comment (user_id, posting_id, comment) values (8, 12, 'Information Systems Manager');
insert into comment (user_id, posting_id, comment) values (1, 6, 'Human Resources Manager');
insert into comment (user_id, posting_id, comment) values (7, 49, 'Programmer II');
insert into comment (user_id, posting_id, comment) values (1, 8, 'Software Test Engineer III');
insert into comment (user_id, posting_id, comment) values (10, 33, 'GIS Technical Architect');
insert into comment (user_id, posting_id, comment) values (8, 28, 'VP Quality Control');
insert into comment (user_id, posting_id, comment) values (6, 4, 'Help Desk Operator');
insert into comment (user_id, posting_id, comment) values (9, 17, 'Social Worker');
insert into comment (user_id, posting_id, comment) values (10, 30, 'Clinical Specialist');
insert into comment (user_id, posting_id, comment) values (1, 35, 'Compensation Analyst');
insert into comment (user_id, posting_id, comment) values (3, 24, 'Nurse');
insert into comment (user_id, posting_id, comment) values (7, 23, 'Sales Representative');
insert into comment (user_id, posting_id, comment) values (5, 44, 'Senior Developer');
insert into comment (user_id, posting_id, comment) values (9, 37, 'Programmer III');


-- migrate:down

