-- migrate:up
insert into Works_Posting (user_id, category_id, title, content, status_id) values (7, 4, 'Madoqua kirkii', 'Displaced oblique fracture of shaft of left radius, subsequent encounter for closed fracture with delayed healing', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (3, 2, 'Cordylus giganteus', 'Occupant (driver) (passenger) of three-wheeled motor vehicle injured in unspecified nontraffic accident, sequela', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (8, 3, 'Macaca mulatta', 'Personal history of other malignant neoplasm of thymus', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (12, 2, 'Spermophilus lateralis', 'Other primary thrombocytopenia', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (12, 3, 'Eubalaena australis', 'Toxic effect of aflatoxin and other mycotoxin food contaminants', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (7, 2, 'Amazona sp.', 'Displaced posterior arch fracture of first cervical vertebra, subsequent encounter for fracture with delayed healing', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (4, 2, 'Meles meles', 'Nondisplaced fracture of medial condyle of right humerus, subsequent encounter for fracture with nonunion', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (5, 4, 'Lutra canadensis', 'Nondisplaced fracture of anterior process of right calcaneus, subsequent encounter for fracture with malunion', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (7, 1, 'Mirounga angustirostris', 'Furuncle of buttock', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (3, 3, 'Spizaetus coronatus', 'Superficial (introital) dyspareunia', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (10, 1, 'Agkistrodon piscivorus', 'Salter-Harris Type III physeal fracture of lower end of right tibia, initial encounter for closed fracture', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (8, 4, 'Cyrtodactylus louisiadensis', 'Recurrent erosion of cornea, bilateral', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (1, 4, 'Microcebus murinus', 'Poisoning by other topical agents, intentional self-harm, sequela', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (12, 4, 'Bassariscus astutus', 'Poisoning by antigonadotrophins, antiestrogens, antiandrogens, not elsewhere classified, accidental (unintentional), initial encounter', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (1, 2, 'Iguana iguana', 'Rheumatoid heart disease with rheumatoid arthritis of right elbow', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (8, 4, 'Camelus dromedarius', 'Nondisplaced spiral fracture of shaft of ulna, left arm, subsequent encounter for open fracture type I or II with delayed healing', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (1, 2, 'Plectopterus gambensis', 'Segmental and somatic dysfunction of lower extremity', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (6, 1, 'Zalophus californicus', 'Drug or chemical induced diabetes mellitus with neurological complications', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (8, 2, 'Macropus eugenii', 'Carbuncle of neck', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (13, 4, 'Scolopax minor', 'Toxic effect of other specified inorganic substances, undetermined, initial encounter', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (12, 3, 'Tragelaphus angasi', 'Nondisplaced fracture of greater trochanter of left femur, sequela', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (8, 4, 'Ammospermophilus nelsoni', 'Placenta accreta, third trimester', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (4, 4, 'Francolinus leucoscepus', 'Unspecified injury of axillary or brachial vein, unspecified side, sequela', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (12, 4, 'Isoodon obesulus', 'Pseudopterygium of conjunctiva, left eye', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (5, 1, 'Felis caracal', 'Poisoning by mineralocorticoids and their antagonists, accidental (unintentional), initial encounter', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (9, 2, 'Damaliscus dorcas', 'Nondisplaced segmental fracture of shaft of ulna, left arm, subsequent encounter for open fracture type I or II with routine healing', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (11, 1, 'Ephippiorhynchus mycteria', 'Pain in unspecified forearm', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (4, 2, 'Chauna torquata', 'Poisoning by, adverse effect of and underdosing of sulfonamides', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (1, 4, 'Hymenolaimus malacorhynchus', 'Complete traumatic amputation of penis, subsequent encounter', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (12, 2, 'Corvus albicollis', 'Traumatic hemopneumothorax, subsequent encounter', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (3, 3, 'Macropus eugenii', 'Disorder of amniotic fluid and membranes, unspecified, third trimester, fetus 1', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (13, 1, 'Lamprotornis nitens', 'Toxic effect of corrosive alkalis and alkali-like substances, undetermined, initial encounter', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (3, 4, 'Axis axis', 'Bone and joint lesions of yaws', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (5, 1, 'Marmota flaviventris', 'Puncture wound with foreign body of unspecified thumb with damage to nail', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (7, 3, 'Centrocercus urophasianus', 'Toxic effect of other tobacco and nicotine, intentional self-harm, sequela', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (4, 4, 'Eudromia elegans', 'Fetal anemia and thrombocytopenia, second trimester, fetus 4', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (6, 1, 'Ara chloroptera', 'Insect bite (nonvenomous) of unspecified eyelid and periocular area, sequela', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (8, 1, 'Melanerpes erythrocephalus', 'Complete traumatic amputation of left great toe, initial encounter', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (3, 2, 'Eudromia elegans', 'Unspecified fracture of upper end of right tibia, initial encounter for open fracture type I or II', 1);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (7, 3, 'Bison bison', 'Military operations involving explosion of depth-charge', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (1, 1, 'Varanus sp.', 'Unspecified occupant of three-wheeled motor vehicle injured in collision with pedestrian or animal in nontraffic accident, sequela', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (5, 3, 'Odocoileus hemionus', 'Frostbite with tissue necrosis of left knee and lower leg, initial encounter', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (5, 4, 'Theropithecus gelada', 'Insect bite (nonvenomous) of unspecified finger', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (11, 4, 'Certotrichas paena', 'Torus fracture of upper end of unspecified fibula, sequela', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (6, 2, 'Tockus flavirostris', 'Dislocation of metacarpophalangeal joint of unspecified finger, subsequent encounter', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (11, 1, 'Bubo sp.', 'Legal intervention involving bayonet, law enforcement official injured, subsequent encounter', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (11, 4, 'Canis mesomelas', 'Unspecified physeal fracture of right calcaneus, initial encounter for closed fracture', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (4, 4, 'unavailable', 'Corrosion of unspecified degree of knee', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (1, 1, 'Phascogale calura', 'Newborn affected by other malpresentation, malposition and disproportion during labor and delivery', 2);
insert into Works_Posting (user_id, category_id, title, content, status_id) values (11, 3, 'Antechinus flavipes', 'Other rupture of muscle (nontraumatic), unspecified upper arm', 2);


insert into upload_file (posting_id, file_sort_id, upload_url) values (2, 1, 'http://dummyimage.com/1905x1708.png/cc0000/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (3, 1, 'http://dummyimage.com/2483x1464.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (4, 1, 'http://dummyimage.com/1552x1767.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (5, 1, 'http://dummyimage.com/716x780.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (6, 1, 'http://dummyimage.com/898x1640.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (7, 1, 'http://dummyimage.com/1496x1024.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (8, 1, 'http://dummyimage.com/844x1882.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (9, 1, 'http://dummyimage.com/1904x883.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (10, 1, 'http://dummyimage.com/985x1226.png/ff4444/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (11, 1, 'http://dummyimage.com/1014x1621.png/cc0000/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (12, 1, 'http://dummyimage.com/2206x923.png/ff4444/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (13, 1, 'http://dummyimage.com/1438x503.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (14, 1, 'http://dummyimage.com/1759x1654.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (15, 1, 'http://dummyimage.com/1636x1666.png/cc0000/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (16, 1, 'http://dummyimage.com/2449x901.png/ff4444/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (17, 1, 'http://dummyimage.com/789x1111.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (18, 1, 'http://dummyimage.com/677x1571.png/cc0000/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (19, 1, 'http://dummyimage.com/1352x1009.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (20, 1, 'http://dummyimage.com/1722x1909.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (21, 1, 'http://dummyimage.com/752x903.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (22, 1, 'http://dummyimage.com/1625x708.png/ff4444/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (23, 1, 'http://dummyimage.com/1817x600.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (24, 1, 'http://dummyimage.com/2121x1068.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (25, 1, 'http://dummyimage.com/1194x726.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (26, 1, 'http://dummyimage.com/1105x1919.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (27, 1, 'http://dummyimage.com/2073x896.png/ff4444/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (28, 1, 'http://dummyimage.com/1959x678.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (29, 1, 'http://dummyimage.com/1508x591.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (30, 1, 'http://dummyimage.com/1915x1437.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (31, 1, 'http://dummyimage.com/998x1613.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (32, 1, 'http://dummyimage.com/1295x1238.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (33, 1, 'http://dummyimage.com/849x1858.png/ff4444/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (34, 1, 'http://dummyimage.com/818x1681.png/ff4444/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (35, 1, 'http://dummyimage.com/1215x1510.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (36, 1, 'http://dummyimage.com/2106x1918.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (37, 1, 'http://dummyimage.com/2416x1820.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (38, 1, 'http://dummyimage.com/1677x1259.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (39, 1, 'http://dummyimage.com/644x1533.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (40, 1, 'http://dummyimage.com/2326x1666.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (41, 1, 'http://dummyimage.com/2059x1560.png/cc0000/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (42, 1, 'http://dummyimage.com/1379x986.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (43, 1, 'http://dummyimage.com/1933x1709.png/5fa2dd/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (44, 1, 'http://dummyimage.com/1649x1675.png/ff4444/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (45, 1, 'http://dummyimage.com/1028x812.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (46, 1, 'http://dummyimage.com/1800x780.png/cc0000/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (47, 1, 'http://dummyimage.com/1304x661.png/cc0000/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (48, 1, 'http://dummyimage.com/960x590.png/dddddd/000000');
insert into upload_file (posting_id, file_sort_id, upload_url) values (49, 1, 'http://dummyimage.com/2089x1012.png/ff4444/ffffff');
insert into upload_file (posting_id, file_sort_id, upload_url) values (50, 1, 'http://dummyimage.com/1761x522.png/dddddd/000000');


-- migrate:down

